version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "sphinx-rtd-theme"
      - dependency-name: "sphinxemoji"
