[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "VaxPress"
platforms = ["linux-64"]
version = "0.9.0"

[tasks]

[dependencies]
python = ">=3.9,<4"
biopython = ">=1.84,<2"
numpy = ">=2.1.1,<3"
pandas = ">=2.2.3,<3"
tqdm = ">=4.66.5,<5"
click = ">=8.1.7,<9"
requests = ">=2.32.3,<3"
scipy = ">=1.14.1,<2"
plotly = ">=5.24.1,<6"
jinja2 = ">=3.1.4,<4"
pylru = ">=1.2.1,<2"
tabulate = ">=0.9.0,<0.10"
snakemake = ">=8.20.4,<9"
google-cloud-sdk = ">=493.0.0,<494"
pip = ">=24.2,<25"
rpy2 = ">=3.5.11,<4"
pre-commit = ">=3.8.0,<4"

[pypi-dependencies]
pytrf = ">=1.3.3, <2"
linearfold-unofficial = ">=0.1, <0.2"
linearpartition-unofficial = ">=0.3, <0.4"
viennarna = ">=2.6.4, <3"
build = ">=1.2.2, <2"
