[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "VaxPress"
platforms = ["linux-64"]
version = "0.9.0"

[tasks]

[dependencies]
biopython = ">=1.84,<2"
numpy = ">=2.1.1,<3"
pandas = ">=2.2.3,<3"
tqdm = ">=4.66.5,<5"
click = ">=8.1.7,<9"
requests = ">=2.32.3,<3"
scipy = ">=1.14.1,<2"
plotly = ">=5.24.1,<6"
jinja2 = ">=3.1.4,<4"
pylru = ">=1.2.1,<2"
tabulate = ">=0.9.0,<0.10"
snakemake = ">=8.20.4,<9"
google-cloud-sdk = ">=493.0.0,<494"

[pypi-dependencies]
pytrf = ">=1.3.3, <2"
